version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    volumes:
      - ./server/database.sqlite:/app/server/database.sqlite
    restart: unless-stopped

